"""The platform API the red agent calls.

Humans are pre-generated by `generate_world`. Bots act only through this
surface. It enforces what a real platform would (targets must exist, no time
travel, no self-engagement), labels every account created here as a bot in
ground truth, and never touches the human event log, so a bot round cannot
change the humans it is hiding among.

Ordering contract: events are ordered by (sim_ts, event_id). Bot event ids
continue after the last human id, so id order alone is not time order.
"""
from __future__ import annotations

from bisect import bisect_right

from simulator.events import Event
from simulator.world import World


class PlatformError(ValueError):
    """The platform refused an action."""


class Platform:
    def __init__(self, world: World) -> None:
        self.world = world
        self.ground_truth: dict[str, str] = dict(world.ground_truth)
        self._human_ts = [e.sim_ts for e in world.events]
        self._posts: dict[str, tuple[int, str]] = {  # post_id -> (sim_ts, author)
            e.post_id: (e.sim_ts, e.account_id) for e in world.events if e.action == "post"
        }
        self._bot_events: list[Event] = []
        self._next_id = len(world.events)
        self._now = 0
        self._created: dict[str, int] = {}  # bot account -> creation sim_ts
        self._ip: dict[str, str] = {}
        self._following: dict[str, set[str]] = {}

    @property
    def human_events(self) -> list[Event]:
        return self.world.events

    @property
    def now(self) -> int:
        return self._now

    def create_account(self, account_id: str, ip: str, sim_ts: int) -> None:
        if not account_id or not ip:
            raise PlatformError("account_id and ip are required")
        if account_id in self.ground_truth:
            raise PlatformError(f"account {account_id!r} already exists")
        self._advance(sim_ts)
        self.ground_truth[account_id] = "bot"  # set by the platform, never by the caller
        self._created[account_id] = sim_ts
        self._ip[account_id] = ip
        self._following[account_id] = set()

    def post(self, account_id: str, sim_ts: int, text: str) -> Event:
        self._check_actor(account_id, sim_ts)
        event = self._emit(account_id, sim_ts, "post", None, text)
        self._posts[event.post_id] = (sim_ts, account_id)
        return event

    def like(self, account_id: str, sim_ts: int, post_id: str) -> Event:
        self._check_actor(account_id, sim_ts)
        self._check_post(account_id, sim_ts, post_id)
        return self._emit(account_id, sim_ts, "like", post_id, None)

    def comment(self, account_id: str, sim_ts: int, post_id: str, text: str) -> Event:
        self._check_actor(account_id, sim_ts)
        self._check_post(account_id, sim_ts, post_id)
        return self._emit(account_id, sim_ts, "comment", post_id, text)

    def follow(self, account_id: str, sim_ts: int, target_id: str) -> Event:
        self._check_actor(account_id, sim_ts)
        if target_id == account_id:
            raise PlatformError("cannot follow yourself")
        if target_id not in self.ground_truth:
            raise PlatformError(f"no such account {target_id!r}")
        if target_id in self._following[account_id]:
            raise PlatformError(f"already following {target_id!r}")
        event = self._emit(account_id, sim_ts, "follow", target_id, None)
        self._following[account_id].add(target_id)
        return event

    def events_until(self, sim_ts: int) -> list[Event]:
        """Every event (human and bot) at or before sim_ts, in (sim_ts, event_id) order."""
        humans = self.world.events[: bisect_right(self._human_ts, sim_ts)]
        bots = [e for e in self._bot_events if e.sim_ts <= sim_ts]
        return sorted(humans + bots, key=lambda e: (e.sim_ts, e.event_id))

    def _advance(self, sim_ts: int) -> None:
        if sim_ts < self._now:
            raise PlatformError(f"time travel: sim_ts {sim_ts} is before the clock at {self._now}")
        self._now = sim_ts

    def _check_actor(self, account_id: str, sim_ts: int) -> None:
        if account_id not in self._created:
            raise PlatformError(f"{account_id!r} is not an account you can act as")
        if sim_ts < self._created[account_id]:
            raise PlatformError(f"{account_id!r} does not exist yet at sim_ts {sim_ts}")
        if sim_ts < self._now:
            raise PlatformError(f"time travel: sim_ts {sim_ts} is before the clock at {self._now}")

    def _check_post(self, account_id: str, sim_ts: int, post_id: str) -> None:
        if post_id not in self._posts:
            raise PlatformError(f"no such post {post_id!r}")
        post_ts, author = self._posts[post_id]
        if post_ts > sim_ts:
            raise PlatformError(f"post {post_id!r} does not exist yet at sim_ts {sim_ts}")
        if author == account_id:
            raise PlatformError("cannot engage with your own post")

    def _emit(self, account_id: str, sim_ts: int, action: str, target: str | None, text: str | None) -> Event:
        try:
            event = Event(self._next_id, sim_ts, account_id, action, target, text, self._ip[account_id])
        except ValueError as exc:  # e.g. empty text on a post
            raise PlatformError(str(exc)) from exc
        self._next_id += 1
        self._now = sim_ts
        self._bot_events.append(event)
        return event
